swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Accounts API
      description: API for fetching all accounts of user (Global, not one by one)
      responses:
        '200':
          description: User accounts get successfuly
          schema:
            $ref: '#/definitions/UserAccounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account:        
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Specific Account API
      description: API for fetching one specific account in another page
      parameters:
        - in: body
          name: body
          description: Get a specific account
          schema:
            $ref: '#/definitions/AccountIDCall'
      produces:
        - application/json
      responses:
        '200':
          description: User account get successfuly
          schema:
            $ref: '#/definitions/AccountInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Change transaction informations
      description: API to change transaction informations
      parameters:
        - in: body
          name: body
          description: Update user transaction informations
          required: true
          schema:
            $ref: '#/definitions/TransactionChanges'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction informations successfuly updated
          schema:
            $ref: '#/definitions/TransactionModified'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
       type: object
       properties:
        accounts:
          type: object
          properties:
            accountID: 
             type: string
             description : ID of each account
            accountName:
             type: string
             description : Account name informations
            balance:
             type: string
             description: Balance of this account
            accountType:
               type: string
            transactionNbrs :
               type: string  
               description : Type of account
  AccountIDCall :
   properties:
    AccountID : 
     type: string
  AccountInformations :
   type: object
   properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
               TransactionID:
                type: string
                description : ID of each trasaction
               Amount:
                type: string
                description: Value of each transaction
               TransationInformations:
                type: string
                description : Desscription of the transaction
  TransactionChanges: 
   properties: 
    transactionInformation : 
     type:  string
  TransactionModified :
   type: object
   properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          newTransactionInfs :
               type: string
               description: New Transaction informations           