swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Accounts API
      description: API for fetching all accounts of user (Global, not one by one)
      responses:
        '200':
          description: User accounts get successfuly / => UserAccounts
          schema:
            $ref: '#/definitions/UserAccounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account:        
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Specific Account API
      description: API for fetching one specific account in another page / =>AccountIDCall
      parameters:
        - in: body
          name: body
          description: Get a specific account 
          schema:
            $ref: '#/definitions/AccountIDCall'
      produces:
        - application/json
      responses:
        '200':
          description: User account get successfuly / =>AccountInformations
          schema:
            $ref: '#/definitions/AccountInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get account transactions for a specific mounth
      description: API for fetching one specific mounth for an account / => AccountPeriodFilter
      parameters:
        - in: body
          name: body
          description: Get a specific period of the account 
          schema:
            $ref: '#/definitions/AccountPeriodFilter'
      produces:
        - application/json
      responses:
        '200':
          description: User account filter get successfuly / => TransactionFiltered
          schema:
            $ref: '#/definitions/TransactionFiltered'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Specific Transaction API
      description: API for fetching one specific transaction / => TransactionIDCall
      parameters:
        - in: body
          name: body
          description: Get a specific account
          schema:
            $ref: '#/definitions/TransactionIDCall'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction get successfuly / => TransactionInformations
          schema:
            $ref: '#/definitions/TransactionInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Change transaction informations
      description: API to change transaction informations / => TransactionsChanges
      parameters:
        - in: body
          name: body
          description: Update user transaction informations 
          required: true
          schema:
            $ref: '#/definitions/TransactionChanges'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction informations successfuly updated / => TransactionModified
          schema:
            $ref: '#/definitions/TransactionModified'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete transaction informations
      description: API to delete transaction informations / => TransactionDelete
      parameters:
        - in: body
          name: body
          description: Delete user transaction informations
          required: true
          schema:
            $ref: '#/definitions/TransactionDelete'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction informations successfuly deleted / => TransactionDeleted
          schema:
            $ref: '#/definitions/TransactionDeleted'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
       type: object
       properties:
        accounts:
          type: object
          properties:
            accountID: 
             type: integer
             description : ID of each account
            accountName:
             type: string
             description : Account name informations
            balance:
             type: string
             description: Balance of this account
            accountType:
               type: string
            transactionNbrs :
               type: string  
               description : Type of account
  AccountIDCall :
   properties:
    AccountID : 
     type: integer
  AccountInformations :
   type: object
   properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
               TransactionID:
                type: integer
                description : ID of each trasaction
               Amount:
                type: string
                description: Value of each transaction
               TransationInformations:
                type: string
                description : Description of the transaction
               TransactionDate:
                type: string
                description: Date of the transaction 
  AccountPeriodFilter:
   properties:
    Mounth:
     type: string
  TransactionFiltered:
   type: object
   properties:
    status: 
     type: integer
    message: 
     type: string
    body:
     type: object
     properties:
      TransactionID: 
       type: integer
      Amount: 
       type: string
      TransactionInformations:
       type: string     
      TransactionDate :
       type: string 

  TransactionChanges: 
   properties: 
    transactionInformation : 
     type:  string
  TransactionModified :
   type: object
   properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          newTransactionInfs :
               type: string
               description: New Transaction informations      
  TransactionIDCall :
   properties :
    transactionID :
     type: integer
  TransactionInformations :
   type: object
   properties: 
    status: 
     type: integer
    message: 
     type: string
    body: 
     type: object
     properties:
      transactionInformations :
       type: string
      amount: 
       type: string
      period: 
       type: string
  TransactionDelete:
   properties: 
    transactionID:
     type: integer
  TransactionDeleted:
   type: object
   properties:
    status: 
     type: integer
    message: 
     type: string

      
